import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { ThemeProvider } from "next-themes";
import ThemeCompo from "./components/ThemeCompo";
import { ClerkProvider } from "@clerk/nextjs";
// This is a custom layout for a Next.js application that uses Clerk for authentication and Next Themes for theming.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Garoum's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ThemeCompo>
              <Header />
              {children}
            </ThemeCompo>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
