import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "next-themes";
import ThemeCompo from "@/components/ThemeCompo";
import Footer from "@/components/Footer";
import AuthProvider from "@/app/AuthProvider";


const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Garoum's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeCompo>
            <AuthProvider>
              <Header />
              {children}
              <Footer />
            </AuthProvider>
          </ThemeCompo>
        </ThemeProvider>
      </body>
    </html>
  );
}
